---
- name: Check docker
  apt:
    name: docker.io
    state: present

- name: Check docker-compose
  apt:
    name: docker-compose
    state: present

- name: Start Docker containers
  command: docker-compose up -d
  args:
    chdir: "{{ playbook_dir }}/app"
