---
- name: Create app dir
  file:
    path: "{{ playbook_dir }}/app"
    state: directory

- name: Copy docker-compose.yml 
  copy:
    src: docker-compose.yml
    dest: "{{ playbook_dir }}/app/docker-compose.yml"

- name: Copy nginx.conf 
  copy:
    src: nginx.conf
    dest: "{{ playbook_dir }}/app/nginx.conf"
